"""add videos templates refactor jobs

Revision ID: 87293661c08a
Revises: a9a7501ce04d
Create Date: 2026-05-04 02:28:48.123056

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '87293661c08a'
down_revision: Union[str, None] = 'a9a7501ce04d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('templates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('blend_key', sa.String(length=512), nullable=False),
    sa.Column('json_key', sa.String(length=512), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('videos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('video_file_key', sa.String(length=512), nullable=False),
    sa.Column('music_key', sa.String(length=512), nullable=False),
    sa.Column('voice_key', sa.String(length=512), nullable=False),
    sa.Column('subtitle_key', sa.String(length=512), nullable=False),
    sa.Column('video_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('jobs', sa.Column('video_id', sa.UUID(), nullable=False))
    op.add_column('jobs', sa.Column('template_id', sa.UUID(), nullable=False))
    op.alter_column('jobs', 'output_key',
               existing_type=sa.VARCHAR(length=512),
               nullable=True)
    op.create_foreign_key(None, 'jobs', 'templates', ['template_id'], ['id'])
    op.create_foreign_key(None, 'jobs', 'videos', ['video_id'], ['id'])
    op.drop_column('jobs', 'template_key')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('template_key', sa.VARCHAR(length=512), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'jobs', type_='foreignkey')
    op.drop_constraint(None, 'jobs', type_='foreignkey')
    op.alter_column('jobs', 'output_key',
               existing_type=sa.VARCHAR(length=512),
               nullable=False)
    op.drop_column('jobs', 'template_id')
    op.drop_column('jobs', 'video_id')
    op.drop_table('videos')
    op.drop_table('templates')
    # ### end Alembic commands ###
